ALTER TYPE "public"."DocumentType" ADD VALUE IF NOT EXISTS 'DIGILOCKER_PHOTO';
ALTER TYPE "public"."DocumentType" ADD VALUE IF NOT EXISTS 'DIGILOCKER_AADHAAR';
ALTER TYPE "public"."DocumentType" ADD VALUE IF NOT EXISTS 'DIGILOCKER_PAN';